-- Total Revenue Generated
USE marketing_attribution;
SELECT
    SUM(Revenue) AS Total_Revenue
FROM `cleaned_marketing_dataset (1)`;

-- Revenue Generated by Each Marketing Channel

SELECT
    UTM_Source,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM `cleaned_marketing_dataset (1)`
GROUP BY UTM_Source
ORDER BY Total_Revenue DESC;

-- Revenue Generated by Each Marketing Channel

SELECT
    UTM_Source,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM `cleaned_marketing_dataset (1)`
GROUP BY UTM_Source
ORDER BY Total_Revenue DESC;

-- Revenue Generated by Campaign

SELECT
    Campaign,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM `cleaned_marketing_dataset (1)`
GROUP BY Campaign
ORDER BY Total_Revenue DESC;

-- Total Conversions

SELECT
    SUM(Converted) AS Total_Conversions
FROM `cleaned_marketing_dataset (1)`;

-- Channel-wise Conversions

SELECT
    UTM_Source,
    SUM(Converted) AS Total_Conversions
FROM `cleaned_marketing_dataset (1)`
GROUP BY UTM_Source
ORDER BY Total_Conversions DESC;

-- Conversion Rate by Marketing Channel

SELECT
    UTM_Source,
    COUNT(*) AS Total_Users,
    SUM(Converted) AS Converted_Users,
    ROUND(
        (SUM(Converted) * 100.0) / COUNT(*),
        2
    ) AS Conversion_Rate_Percentage
FROM `cleaned_marketing_dataset (1)`
GROUP BY UTM_Source
ORDER BY Conversion_Rate_Percentage DESC;

-- Campaign Performance

SELECT
    Campaign,
    COUNT(*) AS Total_Interactions,
    SUM(Converted) AS Total_Conversions,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM `cleaned_marketing_dataset (1)`
GROUP BY Campaign
ORDER BY Total_Revenue DESC;

-- Top 5 Revenue Generating Campaigns

SELECT
    Campaign,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM `cleaned_marketing_dataset (1)`
GROUP BY Campaign
ORDER BY Total_Revenue DESC
LIMIT 5;

-- ROI by Marketing Channel

SELECT
    UTM_Source,
    ROUND(SUM(Revenue),2) AS Revenue,
    ROUND(SUM(Ad_Spend),2) AS Ad_Spend,
    ROUND(
        ((SUM(Revenue)-SUM(Ad_Spend))
        / SUM(Ad_Spend))*100,
        2
    ) AS ROI_Percentage
FROM `cleaned_marketing_dataset (1)`
GROUP BY UTM_Source
ORDER BY ROI_Percentage DESC;

-- Overall Channel Performance

SELECT
    UTM_Source,
    SUM(Converted) AS Conversions,
    ROUND(SUM(Revenue),2) AS Revenue,
    ROUND(SUM(Ad_Spend),2) AS Ad_Spend
FROM `cleaned_marketing_dataset (1)`
GROUP BY UTM_Source
ORDER BY Revenue DESC;
